---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n8ad1f5/dailyspark.info
    - /bin/cp -R ./* $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || :